// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSystem(arg1) {
  return window['go']['main']['App']['AddSystem'](arg1);
}

export function ConnectSystem(arg1, arg2) {
  return window['go']['main']['App']['ConnectSystem'](arg1, arg2);
}

export function CreateComment(arg1, arg2) {
  return window['go']['main']['App']['CreateComment'](arg1, arg2);
}

export function CreateSigs(arg1, arg2) {
  return window['go']['main']['App']['CreateSigs'](arg1, arg2);
}

export function GetActiveChain() {
  return window['go']['main']['App']['GetActiveChain']();
}

export function ImportChain() {
  return window['go']['main']['App']['ImportChain']();
}

export function NewChain(arg1) {
  return window['go']['main']['App']['NewChain'](arg1);
}

export function SaveChain() {
  return window['go']['main']['App']['SaveChain']();
}
