// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSystem(arg1:main.System):Promise<void>;

export function ConnectSystem(arg1:string,arg2:string):Promise<void>;

export function CreateComment(arg1:string,arg2:string):Promise<void>;

export function CreateSigs(arg1:string,arg2:string):Promise<void>;

export function GetActiveChain():Promise<main.Chain>;

export function ImportChain():Promise<main.Chain>;

export function NewChain(arg1:main.System):Promise<main.Chain>;

export function SaveChain():Promise<void>;
